void rgb_port_config (void)
{
  /*****************************************
    Define DDR and PORT values for the port on which RGB LED is connected
  ******************************************/
  DDRA |= 0xE0;
  PORTA |= 0xE0;
}

void color_sensor_pin_config(void)
{
  /*****************************************
    Define DDR and PORT values for the port on which Color sensor is connected
  ******************************************/
  DDRA |= (1 << S0) | (1 << S1) | (1 << S2) | (1 << S3);
  DDRD &= ~(1 << OUT);
  //PORTA |= 0x0F;
}


void color_sensor_pin_interrupt_init(void) //Interrupt 0 enable
{
  cli(); //Clears the global interrupt
  EICRA |= (1 << ISC01); // INT0 is set to trigger with falling edge
  EICRA &= ~(1 << ISC00);
  //EICRA = (1<<ISC01)|(1<<ISC00);
  EIMSK |= (1 << INT0); // Enable Interrupt INT0 for color sensor
  sei(); // Enables the global interrupt
}

//ISR for color sensor
ISR(INT0_vect) // Pass the timer number in place of n in INTn_vect
{
  //increment on receiving pulse from the color sensor
  pulse++;
}

void init_devices(void)
{
  cli(); //Clears the global interrupt
  //Initialize all the ports here
  color_sensor_pin_interrupt_init();
  sei();   // Enables the global interrupt
}

//Filter Selection
void filter_red(void)    //Used to select red filter
{
  //Filter Select - red filter
  PORTA &= ~(1 << S2); //set S2 low
  PORTA &= ~(1 << S3); //set S3 low
}

void filter_green(void) //Used to select green filter
{
  //Filter Select - green filter
  PORTA |= (1 << S2); //set S2 High
  PORTA |= (1 << S3); //set S3 High
}

void filter_blue(void)  //Used to select blue filter
{
  //Filter Select - blue filter
  PORTA &= ~(1 << S2); //set S2 low
  PORTA |= (1 << S3); //set S3 High
}

void filter_clear(void) //select no filter
{
  //Filter Select - no filter
  PORTA |= (1 << S2); //set S2 High
  PORTA &= ~(1 << S3); //set S3 Low
}

//Color Sensing Scaling
void color_sensor_scaling()   //This function is used to select the scaled down version of the original frequency of the output generated by the color sensor, generally 20% scaling is preferable, though you can change the values as per your application by referring datasheet
{
  //Output Scaling 20% from datasheet

  PORTA |= (1 << S0); //set S0 high
  PORTA |= (1 << S1); //set S1 high
}

void red_read(void) // function to select red filter and display the count generated by the sensor on LCD. The count will be more if the color is red. The count will be very less if its blue or green.
{
  //Red
  filter_red();//select red filter
  pulse = 0;//reset the count to 0
  _delay_ms(100);//capture the pulses for 100 ms or 0.1 second
  red = pulse;//store the count in variable called red
}

void green_read(void) // function to select green filter and display the count generated by the sensor on LCD. The count will be more if the color is green. The count will be very less if its blue or red.
{
  //Green
  filter_green();//select green filter
  pulse = 0;//reset the count to 0
  _delay_ms(100);//capture the pulses for 100 ms or 0.1 second
  green = pulse;//store the count in variable called green
}

void blue_read(void) // function to select blue filter and display the count generated by the sensor on LCD. The count will be more if the color is blue. The count will be very less if its red or green.
{
  //Blue
  filter_blue(); //select blue filter
  pulse = 0; //reset the count to 0
  _delay_ms(100); //capture the pulses for 100 ms or 0.1 second
  blue = pulse;  //store the count in variable called blue
}

/*
*
*Function Name: pulseCount
*Input: void
*Output void
*Logic: Reads the values of the proximity and colour sensors and assigns to global variables
*Example call: pulseCount();
*
*/
void pulseCount(void)
{
	red_read();
	blue_read();
	green_read();
}